export var AppConfigFile={
    "application":{
        "table":"application",
        "field":[
			"id",
            "objective",
			"testing_status",
			"application_master_id",
			"release_id",
			"end_date",
			"start_date"
        ]
    },
	"ALIAS_SCORING":{
        "table":"ALIAS_SCORING",
        "field":[
			"ID",
            "FROMBUID",
            "FROMLOCALCHANNEL",
            "TOLOCALCHANNEL",
            "ENABLE",
            "STARTDATE"
        ]
    },
    "auth_codes":{
        "table":"AUTH_CODES",
        "field":[
            "ID",
            "FROMBUID",
            "FROMTRENDVARIABLE",
            "TOTRENDVALUE",
        ]
    },
    "avsGroups":{
        "table":"avsGroups",
        "field":[
            "FROMBUID",
            "TOBUID"
        ]
    }
}